/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\Macbookpro.glb --transform 
Files: .\Macbookpro.glb [285.62KB] > Macbookpro-transformed.glb [858.35KB] (-201%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Macbookpro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={materials.PaletteMaterial001} position={[0, 0, 1.032]} />
      <mesh geometry={nodes['Ref-keyText'].geometry} material={materials.PaletteMaterial002} position={[0, 0, 1.032]} />
    </group>
  )
}

useGLTF.preload('/Macbookpro-transformed.glb')
