/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\TV2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TV2(props) {
  const { nodes, materials } = useGLTF('/models/TV2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TV_Main_0.geometry} material={materials.Main} />
      <mesh geometry={nodes.TV_Screen_0.geometry} material={materials.Screen} />
      <mesh geometry={nodes.Selector_Main_0.geometry} material={materials.Main} />
      <mesh geometry={nodes.Switch_Main_0.geometry} material={materials.Main} />
    </group>
  )
}

useGLTF.preload('/models/TV2.glb')
